openapi: '3.0.3'
info:
  title: Katalog API
  version: '1.0'
servers:
  - url: http://localhost:50001
  - url: http://ocp4.de:50001
paths:
  /articles:
    get:
      tags:
        - Shop  
      summary: Get all Artikels
      description: Articles will be provided
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'

components:
  schemas:
    Article:
      type: object
      properties:
        name:
          type: string
          maxLength: 45
          description: This is the name of the article
          example: Cherry
        price:
          type: number
          minimum: 0
          description: This is the price to sell
          example: 0.99
      required:
        - name
        - price
